### ISSUE TITLE
我测试php 7.1 与PHP7.0 发现 createDragbleImg() 里面imagecolortransparent($imgCrop,$this->colorTransparentInt);未生效如图

### ISSUE THREAD

**Issue by yetHandsome** [jobsfan/image_drag_auth#1]
[
![image](https://user-images.githubusercontent.com/35953746/54215046-36141080-4522-11e9-9809-c56f31148dde.png)
](url)

**Comment by jobsfan** [comment]
我https://www.wendangs.com/api/imagedragauth/demo 这个demo是写在zf3框架里面，php版本是7.0.32，妥妥的没问题啊，7.1我没有测试

666，我去你的github看了下，你把我这个破解了，还把bug也修复了 :)
